// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVbDb2VX7_SVWUXil8ZJV6HEWOi-tQPPE',
    appId: '1:596670531979:web:bde16006621b360b1d478e',
    messagingSenderId: '596670531979',
    projectId: 'lab3mis',
    authDomain: 'lab3mis.firebaseapp.com',
    storageBucket: 'lab3mis.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjpdWZxx-vLMSqEZQe8_matnl4T6zsSjM',
    appId: '1:596670531979:android:bc4cf2214faede9a1d478e',
    messagingSenderId: '596670531979',
    projectId: 'lab3mis',
    storageBucket: 'lab3mis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsTCSCO3XWdk5aGua9nOiMVxfWYy74vP4',
    appId: '1:596670531979:ios:49e1196559ee58281d478e',
    messagingSenderId: '596670531979',
    projectId: 'lab3mis',
    storageBucket: 'lab3mis.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsTCSCO3XWdk5aGua9nOiMVxfWYy74vP4',
    appId: '1:596670531979:ios:49e1196559ee58281d478e',
    messagingSenderId: '596670531979',
    projectId: 'lab3mis',
    storageBucket: 'lab3mis.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVbDb2VX7_SVWUXil8ZJV6HEWOi-tQPPE',
    appId: '1:596670531979:web:70fe55f48301781f1d478e',
    messagingSenderId: '596670531979',
    projectId: 'lab3mis',
    authDomain: 'lab3mis.firebaseapp.com',
    storageBucket: 'lab3mis.firebasestorage.app',
  );
}
